### PR TITLE
Use transparent string to fix config error

### PR DESCRIPTION
**Pull request by coryzibell**
Transparent is undefined, needs to be wrapped as a string

### CODE REVIEW

**Comment by coryzibell** [comment]
Thanks for merging the pull request @jcklpe ! Would you mind publishing the update on NPM so I can use the package in hyper without having to specify a local file? Thanks!

**Comment by jcklpe** [comment]
@coryzibell Sure thing, I'm going to do that ASAP. My laptop just died so I'm in the process of rejiggering some stuff. If you know of anyway that I can pass credentials on to you so you can also update the npm though let me know. I'm still pretty new to development so I don't know if that's possible but it seems like it should be right?

**Comment by coryzibell** [comment]
Thanks! Yeah from the local repo when you are logged into npm you can do `npm owner add coryzibell`

**Comment by jcklpe** [comment]
Awesome! Done! Also I went ahead and published the update since I had stuff working. :) 

Thanks for fixing that. I haven't been running hyperpunk lately because I was getting killer slowdown on my cpu, but I think this means I'll have to try it out again to see how it runs now that I've got a new computer

**Pull request merged**
